# Generated by Django 5.2.10 on 2026-01-17 10:52

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitem',
            old_name='popular',
            new_name='is_popular',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='user_email',
            new_name='customer_email',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='user_name',
            new_name='customer_name',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='phone',
            new_name='customer_phone',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='name_snapshot',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='price_snapshot',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='order',
            name='special_instructions',
        ),
        migrations.AddField(
            model_name='order',
            name='instructions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='order_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='line_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='category',
            field=models.CharField(choices=[('Starters', 'Starters'), ('Main Course', 'Main Course'), ('Beverages', 'Beverages'), ('Desserts', 'Desserts')], max_length=50),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=Decimal('4.0'), max_digits=2),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('30.00'), max_digits=8),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('COD', 'COD'), ('PhonePe', 'PhonePe'), ('GPay', 'GPay'), ('Paytm', 'Paytm')], max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(default='Placed', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
